version: '3'

services:
  app-serve:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: always
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - APP_URL=localhost:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /home/sistemas/PHP e Selenium - Testes de ponta a ponta/.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - /home/sistemas/PHP e Selenium - Testes de ponta a ponta/projeto-web:/var/www/html
    #networks:
      #- selenium-network
    links:
      - selenium-hub
    #command: dockerize -wait tcp://selenium-hub:4200
    #depends_on:
      #- app-serve
      #- selenium-hub

  chrome:
    image: selenium/node-chrome:4.1.1-20211217
    shm_size: 2gb
    #depends_on:
      #- selenium-hub
      #- app-serve
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
      - "7900:7900"
    #networks:
      #- selenium-network
    links:
      - selenium-hub
  
  #app-e2e-tests:
   #image: myapp
   #command: dockerize -wait tcp://app-serve:4200 
        #-wait tcp://backend:8000 
        #-wait tcp://selenium-chrome-standalone:4444 -timeout 10s 
        #-wait-retry-interval 1s bash -c "npm run e2e:docker"
   #depends_on:
     #- app-serve
     #- selenium-hub

  selenium-hub:
    image: selenium/hub:4.1.1-20211217
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  
#networks:
  #selenium-network:
    # external: true
    #driver: bridge